# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Faculty_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Listing_Table',
            fields=[
                ('coursenumber', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('coursetitle', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_Table',
            fields=[
                ('facultyname', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating_Average',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usefulness', models.FloatField()),
                ('lecture_quality', models.FloatField()),
                ('overall_quality', models.FloatField()),
                ('oral_written_tests_helpful', models.FloatField()),
                ('learned_much_info', models.FloatField()),
                ('rating_count', models.IntegerField()),
                ('course_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crank.Course_Faculty_Table')),
            ],
        ),
        migrations.CreateModel(
            name='Rating_id',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usefulness', models.IntegerField()),
                ('lecture_quality', models.IntegerField()),
                ('overall_quality', models.IntegerField()),
                ('oral_written_tests_helpful', models.IntegerField()),
                ('learned_much_info', models.IntegerField()),
                ('course_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crank.Course_Faculty_Table')),
                ('uni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course_faculty_table',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crank.Course_Listing_Table'),
        ),
        migrations.AddField(
            model_name='course_faculty_table',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crank.Faculty_Table'),
        ),
        migrations.AlterUniqueTogether(
            name='rating_id',
            unique_together=set([('uni', 'course_faculty')]),
        ),
        migrations.AlterUniqueTogether(
            name='course_faculty_table',
            unique_together=set([('course', 'faculty')]),
        ),
    ]
