# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating_Average',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usefulness', models.FloatField()),
                ('lecture_quality', models.FloatField()),
                ('overall_quality', models.FloatField()),
                ('oral_written_tests_helpful', models.FloatField()),
                ('learned_much_info', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crank.Course_Faculty_Table')),
            ],
        ),
    ]
