# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating_id',
            name='comments',
            field=models.CharField(default=" ", max_length=2000),
            preserve_default=False,
        ),
    ]
