# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0002_rating_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_average',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
