# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0003_auto_20171110_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_average',
            name='course',
            field=models.CharField(max_length=128),
        ),
    ]
