# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crank', '0004_auto_20171110_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating_average',
            name='id',
        ),
        migrations.AlterField(
            model_name='rating_average',
            name='course',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
